spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    testWhileIdle: true
    validationQuery: SELECT 1
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: system
    password: oracle
    driver:
      class: oracle.jdbc.driver.OracleDriver

---
spring:
  profiles: cf
  datasource:
    url: ${DATASOURCE_JDBC_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
